[package]
name = "rspirv"
version = "0.5.1"
authors = ["Lei Zhang <antiagainst@gmail.com>"]

description = "Rust library APIs for SPIR-V module manipulation"
documentation = "https://docs.rs/rspirv"
repository = "https://github.com/google/rspirv"
readme = "README.md"
license = "Apache-2.0"
keywords = ["spirv", "vulkan", "opengl", "opencl"]

[lib]
path = "lib.rs"

[badges]
travis-ci = { repository = "google/rspirv" }
appveyor = { repository = "antiagainst/rspirv" }

[dependencies]
num = "0.1"
derive_more = "0.7"
clippy = { version = "0.0", optional = true }


[dependencies.spirv_headers]
version = "1.3"
path = "../spirv"

[dev-dependencies]
assert_matches = "1.1"
