os: Visual Studio 2015

version: "{build}"

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV && cargo -vV

build_script:
  - cd codegen
  - cargo build --verbose
  - cd ..\spirv
  - cargo build --verbose
  - cd ..\rspirv
  - cargo build --verbose
  - cd ..\dis
  - cargo build

test_script:
  - cd ..\rspirv
  - cargo test --verbose
